l3_b_keys = ['ZTravel',
            'oneweight',
            'COGZ',
            'COGZSigma',
            'TrueEnergy', 
            'TrueZenith', 
            'TrueAzimuth', 
            'PrimaryType', 
            'RLogL', 
            'RecoAzimuth', 
            'RecoZenith', 
            'weights', 
            'QTot', 
            'LDir_A', 
            'NDirPulse_A',
            'NDirDOM_A',
            'NDirStr_A',
            'LDir_B',
            'NDirPulse_B',
            'NDirDOM_B',
            'NDirStr_B',
            'LDir_C',
            'NDirPulse_C',
            'NDirDOM_C',
            'NDirStr_C',
            'LDir_D',
            'NDirPulse_D',
            'NDirDOM_D',
            'NDirStr_D',
            'LDir_E',
            'NDirPulse_E',
            'NDirDOM_E',
            'NDirStr_E',
            'RecoAngSep',
            'BayesRatio'
           ]

l3_a_keys = ['ZTravel',
            'oneweight',
            'COGZ',
            'COGZSigma',
            'TrueEnergy',
            'TrueZenith',
            'TrueAzimuth',
            'PrimaryType',
            'RLogL',
            'RecoAzimuth',
            'RecoZenith',
            'weights',
            'QTot'
           ]

outkeys_dict = {
                'l3_a':l3_a_keys,
                'l3_b':l3_b_keys,
               }
