l3_b_descs = [
              # MC quantities
              ('oneweight',     '<f8'),
              ('eff_oneweight', '<f8'),
              ('TrueEnergy',    '<f8'),
              ('TrueZenith',    '<f8'),
              ('TrueAzimuth',   '<f8'),
              ('PrimaryType',   '<f8'),
              # Reco quantities
              ('ZTravel',       '<f8'),
              ('COGZ',          '<f8'),
              ('COGZSigma',     '<f8'),
              ('RLogL',         '<f8'),
              ('RecoAzimuth',   '<f8'),
              ('RecoZenith',    '<f8'),
              ('QTot',          '<f8'),
              ('LDir_A',        '<f8'),
              ('NDirPulse_A',   '<f8'),
              ('NDirDOM_A',     '<f8'),
              ('NDirStr_A',     '<f8'),
              ('LDir_B',        '<f8'),
              ('NDirPulse_B',   '<f8'),
              ('NDirDOM_B',     '<f8'),
              ('NDirStr_B',     '<f8'),
              ('LDir_C',        '<f8'),
              ('NDirPulse_C',   '<f8'),
              ('NDirDOM_C',     '<f8'),
              ('NDirStr_C',     '<f8'),
              ('LDir_E',        '<f8'),
              ('NDirPulse_E',   '<f8'),
              ('NDirDOM_E',     '<f8'),
              ('NDirStr_E',     '<f8'),
              ('RecoAngSep',    '<f8'),
              ('BayesRatio',    '<f8'),
             ]

l3_a_descs = [
              ('ZTravel',     '<f8'),
              ('oneweight',   '<f8'),
              ('COGZ',        '<f8'),
              ('COGZSigma',   '<f8'),
              ('TrueEnergy',  '<f8'),
              ('TrueZenith',  '<f8'),
              ('TrueAzimuth', '<f8'),
              ('PrimaryType', '<f8'),
              ('RLogL',       '<f8'),
              ('RecoAzimuth', '<f8'),
              ('RecoZenith',  '<f8'),
              ('weights',     '<f8'),
              ('QTot',        '<f8'),
             ]

outdescs_dict = {
                 'l3_a':l3_a_descs,
                 'l3_b':l3_b_descs,
                }
